name: Deploy docs

on:
  push:
    branches:
      - master
      - beta
      - alpha
    paths:
      - 'docs/**'

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - working-directory: packages/vue-quill2
        run: npm ci
      - name: Build docs
        working-directory: docs
        run: |
          npm ci
          npm run build
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/content/.vitepress/dist
